endpoint:
  health:
    enabled: true
    id: health
    sensitive: false
spring:
  security:
    user:
      password: FpmJj24y9RRRYQnpXXOHEIEJK6lwPjnY09
server:
  tomcat:
    remote-ip-header: "x-forwarded-for"
    protocol-header: "x-forwarded-proto"

app:
  service-info:
    id:
    name:
    description:
    documentation-url:
    contact-url:
    version: