endpoint:
  health:
    enabled: true
    id: health
    sensitive: false

server:
  port: 8089
  tomcat:
    remote-ip-header: "x-forwarded-for"
    protocol-header: "x-forwarded-proto"

cors:
  urls: http://localhost:8089


app:
  service-info:
    id:
    name: "GA4GH Discovery Search API"
    description:
    documentation-url:
    contact-url:
    version:

presto:
  datasource:
    url: "http://localhost:8079"
    username: "ga4gh-search-adapter-presto"
  results:
    default-page-size: 100
  hidden-catalogs: "system,postgrestest"

info:
  build:
    name: "GA4GH Discovery Search API"
    version: 1.0


logging:
  level:
    com.dnastack.ga4gh.search.adapter.presto.PrestoHttpClient: DEBUG # logs queries when search fails

spring:
  jackson:
    default-property-inclusion: NON_NULL
---

spring:
  profiles: default

app:
  # Sample Auth configuration - works with local Wallet, Gatekeeper, Presto (see README.md)
  auth:
    token-issuers:
      - issuer-uri: http://localhost:8081
        jwk-set-uri: http://localhost:8081/oauth/jwks
    presto-oauth-client:
      token-uri: http://localhost:8081/oauth/token
      client-id: ga4gh-search-adapter-presto
      client-secret: dev-secret-never-use-in-prod
      audience: http://presto.local

---

spring:
  profiles: basic-auth
  security:
    user:
      password: FpmJj24y9RRRYQnpXXOHEIEJK6lwPjnY09


---

spring:
  profiles: no-auth
  security:
    enabled: false
  liquibase:
    enabled: false
  datasource:
    continue-on-error: true
management:
  health:
    db:
      enabled=false: