endpoint:
  health:
    enabled: true
    id: health
    sensitive: false

server:
  tomcat:
    remote-ip-header: "x-forwarded-for"
    protocol-header: "x-forwarded-proto"

cors:
  urls: http://localhost:8080


app:
  service-info:
    id:
    name: "GA4GH Discovery Search API"
    description:
    documentation-url:
    contact-url:
    version:

# Sample Auth configuration
#  auth:
#    token-issuers:
#      - issuer-uri: https://wallet.staging.dnastack.com
#      jwk-set-uri: https://wallet.staging.dnastack.com/oauth/jwks
#    presto-oauth-client:
#      token-uri: https://wallet.staging.dnastack.com/oauth/token
#      client-id: some-client
#      client-secret: my-secret
#      audience: the-audience

presto:
  datasource:
    url: "jdbc:presto://presto-public.staging.dnastack.com:443"
    username: "ga4gh-search-adapter-presto"
  results:
    default-page-size: 100
info:
  build:
    name: "GA4GH Discovery Search API"
    version: 1.0

---

spring:
  profiles: basic-auth
  security:
    user:
      password: FpmJj24y9RRRYQnpXXOHEIEJK6lwPjnY09


---

spring:
  profiles: no-auth
  security:
    enabled: false