endpoint:
  health:
    enabled: true
    id: health
    sensitive: false

server:
  port: 8089
  tomcat:
    remote-ip-header: "x-forwarded-for"
    protocol-header: "x-forwarded-proto"

cors:
  urls: http://localhost:8089

app:
  url: http://localhost:${server.port}
  service-info:
    id:
    name: "GA4GH Discovery Search API"
    description:
    documentation-url:
    contact-url:
    version:
  # Un-comment the following section of tables-registry if you would like to enable the flow of fetching the table schema from tables-registry
  # Get the staging secret corresponding to client-id from kubernetes or create your own if pointing to local wallet
  # tables-registry:
    # url: https://ga4gh-tables-registry.staging.dnastack.com
    # auth:
      # authentication-uri: https://wallet.staging.dnastack.com/oauth/token
      # client-id: search-presto-public-client-credentials
      # client-secret: <kubernetes_secret>
      # audience: https://ga4gh-tables-registry.staging.dnastack.com

presto:
  datasource:
    url: "http://localhost:8091"
    username: "ga4gh-search-adapter-presto"
  results:
    default-page-size: 100
  hidden-catalogs: "system"

info:
  build:
    name: "GA4GH Discovery Search API"
    version: 1.0


logging:
  level:
    com.dnastack.ga4gh.search.adapter.presto.PrestoHttpClient: DEBUG # logs queries when search fails

spring:
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://127.0.0.1/ga4ghsearchadapterpresto
    username: ga4ghsearchadapterpresto
    password: ga4ghsearchadapterpresto
    driver-class-name: org.postgresql.Driver

management:
  metrics:
    export:
      logging-monitor:
        enabled: true
      environment: local
---

spring:
  profiles: default

app:
  # Sample Auth configuration - works with local Wallet, Gatekeeper, Presto (see README.md)
  auth:
    authorization-type: bearer
    access-evaluator: scope
    global-method-security:
      enabled: true

    token-issuers:
      - issuer-uri: http://localhost:8081
        jwk-set-uri: http://localhost:8081/oauth/jwks
        audiences: ["http://localhost:${server.port}", "http://search-presto.local"]

    presto-oauth-client:
      token-uri: http://localhost:8081/oauth/token
      client-id: ga4gh-search-adapter-presto
      client-secret: dev-secret-never-use-in-prod
      audience: http://presto.local
---

spring:
  profiles: wallet-auth

app:
  auth:
    authorization-type: bearer
    access-evaluator: wallet
    global-method-security:
      enabled: true

    token-issuers:
      - issuer-uri: http://localhost:8081
        jwk-set-uri: http://localhost:8081/oauth/jwks
        audiences: ["http://localhost:${server.port}", "http://search-presto.local"]

    presto-oauth-client:
      token-uri: http://localhost:8081/oauth/token
      client-id: ga4gh-search-adapter-presto
      client-secret: dev-secret-never-use-in-prod
      audience: http://presto.local
---

spring:
  profiles: no-auth
  security:
    enabled: false
  liquibase:
    enabled: true
  datasource:
    continue-on-error: true
management:
  health:
    db:
      enabled=false:

app:
  auth:
    authorization-type: none
    global-method-security:
      enabled: false
---

spring:
  profiles: basic-auth

app:
  auth:
    authorization-type: basic
    global-method-security:
      enabled: false
